"""Init

Revision ID: 7049ab408a04
Revises: 
Create Date: 2024-05-12 22:17:32.862639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7049ab408a04'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('is_run', sa.Boolean(), nullable=False),
    sa.Column('check_interval', sa.Integer(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_table('from_dirs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tasks_id', sa.Integer(), nullable=False),
    sa.Column('path_from_dir', sa.String(), nullable=False),
    sa.Column('del_after_copy', sa.Boolean(), nullable=False),
    sa.Column('del_not_copy_files', sa.Boolean(), nullable=False),
    sa.Column('backup_not_copy_files', sa.Boolean(), nullable=False),
    sa.Column('path_backup_dir_not_copy_files', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['tasks_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('last_operations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tasks_id', sa.Integer(), nullable=False),
    sa.Column('operation', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('status_ok', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['tasks_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('copy_extensions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_dirs_id', sa.Integer(), nullable=False),
    sa.Column('extension', sa.String(), nullable=False),
    sa.Column('min_size_file', sa.Integer(), nullable=False),
    sa.Column('max_size_file', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['from_dirs_id'], ['from_dirs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('to_dirs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_dirs_id', sa.Integer(), nullable=False),
    sa.Column('path_to_dir', sa.String(), nullable=False),
    sa.Column('is_backup_dir_not_copy_files', sa.Boolean(), nullable=False),
    sa.Column('create_dir_day', sa.Boolean(), nullable=False),
    sa.Column('create_dir_hour', sa.Boolean(), nullable=False),
    sa.Column('create_dir_extension', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['from_dirs_id'], ['from_dirs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('to_dirs')
    op.drop_table('copy_extensions')
    op.drop_table('last_operations')
    op.drop_table('from_dirs')
    op.drop_table('tasks')
    # ### end Alembic commands ###
