"""Initial DB

Revision ID: 737285099091
Revises: 
Create Date: 2024-05-10 09:53:28.987083

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "737285099091"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tasks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("task_enable", sa.Boolean(), nullable=True),
        sa.Column("check_interval", sa.Integer(), nullable=True),
        sa.Column("notes", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "from_dirs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tasks_id", sa.Integer(), nullable=False),
        sa.Column("path_from_dir", sa.String(), nullable=False),
        sa.Column("del_after_copy", sa.Boolean(), nullable=True),
        sa.Column("del_not_copy_files", sa.Boolean(), nullable=True),
        sa.Column("backup_not_copy_files", sa.Boolean(), nullable=True),
        sa.Column(
            "path_backup_dir_not_copy_files", sa.String(), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["tasks_id"],
            ["tasks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "last_operations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tasks_id", sa.Integer(), nullable=False),
        sa.Column("operation", sa.String(), nullable=True),
        sa.Column("timestamp", sa.DateTime(), nullable=True),
        sa.Column("status_ok", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["tasks_id"],
            ["tasks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "copy_extensions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("from_dirs_id", sa.Integer(), nullable=False),
        sa.Column("extension", sa.String(), nullable=False),
        sa.Column("min_size_file", sa.Integer(), nullable=False),
        sa.Column("max_size_file", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["from_dirs_id"],
            ["from_dirs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "to_dirs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("from_dirs_id", sa.Integer(), nullable=False),
        sa.Column("path_to_dir", sa.String(), nullable=False),
        sa.Column("is_backup_dir_not_copy_files", sa.Boolean(), nullable=True),
        sa.Column("create_dir_day", sa.Boolean(), nullable=True),
        sa.Column("create_dir_hour", sa.Boolean(), nullable=True),
        sa.Column("create_dir_extension", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["from_dirs_id"],
            ["from_dirs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("to_dirs")
    op.drop_table("copy_extensions")
    op.drop_table("last_operations")
    op.drop_table("from_dirs")
    op.drop_table("tasks")
    # ### end Alembic commands ###
