"""Initial migrations

Revision ID: a90eeb4405ae
Revises: 
Create Date: 2024-04-24 15:58:01.702502

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a90eeb4405ae"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tasks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("from_dirs", sa.JSON(), nullable=False),
        sa.Column("to_dirs", sa.JSON(), nullable=False),
        sa.Column("task_enable", sa.Boolean(), nullable=True),
        sa.Column("check_interval", sa.Integer(), nullable=True),
        sa.Column("last_operation", sa.JSON(), nullable=True),
        sa.Column("notes", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tasks")
    # ### end Alembic commands ###
