"""edit model schemas

Revision ID: ac0d4e009347
Revises: 1c92308b8434
Create Date: 2024-05-11 10:58:13.554227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac0d4e009347'
down_revision: Union[str, None] = '1c92308b8434'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False))
    op.add_column('tasks', sa.Column('updated_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False))
    op.alter_column('tasks', 'is_run',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('tasks', 'check_interval',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'check_interval',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('tasks', 'is_run',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('tasks', 'updated_at')
    op.drop_column('tasks', 'created_at')
    # ### end Alembic commands ###
