"""change table From_dir

Revision ID: 307bb6f12261
Revises: 1a5ba52d90c5
Create Date: 2024-04-24 20:27:03.019696

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "307bb6f12261"
down_revision: Union[str, None] = "1a5ba52d90c5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "from_dir",
        sa.Column("del_not_copy_files", sa.Boolean(), nullable=True),
    )
    op.add_column(
        "from_dir",
        sa.Column("backup_not_copy_files", sa.Boolean(), nullable=True),
    )
    op.add_column(
        "from_dir",
        sa.Column("backup_dir_not_copy_files", sa.String(), nullable=True),
    )
    op.add_column(
        "from_dir",
        sa.Column(
            "create_dir_day_not_copy_files", sa.Boolean(), nullable=True
        ),
    )
    op.add_column(
        "from_dir",
        sa.Column(
            "create_dir_hour_not_copy_files", sa.Boolean(), nullable=True
        ),
    )
    op.add_column(
        "from_dir",
        sa.Column(
            "create_dir_extension_not_copy_files", sa.Boolean(), nullable=True
        ),
    )
    op.drop_column("from_dir", "not_copy_extensions")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "from_dir",
        sa.Column(
            "not_copy_extensions",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("from_dir", "create_dir_extension_not_copy_files")
    op.drop_column("from_dir", "create_dir_hour_not_copy_files")
    op.drop_column("from_dir", "create_dir_day_not_copy_files")
    op.drop_column("from_dir", "backup_dir_not_copy_files")
    op.drop_column("from_dir", "backup_not_copy_files")
    op.drop_column("from_dir", "del_not_copy_files")
    # ### end Alembic commands ###
