"""drop table From_extension_not_copy

Revision ID: 78bcbe2839d9
Revises: 307bb6f12261
Create Date: 2024-04-24 20:36:01.413812

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "78bcbe2839d9"
down_revision: Union[str, None] = "307bb6f12261"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("file_extension_not_copy")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "file_extension_not_copy",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "from_dir_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "extension", sa.VARCHAR(), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["from_dir_id"],
            ["from_dir.id"],
            name="file_extension_not_copy_from_dir_id_fkey",
        ),
        sa.PrimaryKeyConstraint("id", name="file_extension_not_copy_pkey"),
    )
    # ### end Alembic commands ###
